name: Deploy Laravel Project on push to cpanel
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_Server }}
          username: ${{ secrets.FTP_Username }}
          password: ${{ secrets.FTP_Password }}
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/bootstrap/**
            **/database/**
            **/public/**
            **/storage/**
            **/stubs/**
            **/tests/**
            **/vendor/**
            **.env
